# TESTING AUTH ENDPOINTS

### LOGIN
POST http://127.0.0.1:3000/auth/signin
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "john"
}

### CURRENT USER LOGGED
GET http://127.0.0.1:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGRvZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRUV3hBSE1uNGJqTTJaUjRPajIyYXUubE8vWHllVlpPUHR1TzJVNUlKVi8yeC5DWE5LRjBQUyIsImlhdCI6MTYzMDg4OTY2NiwiZXhwIjoxNjMwOTc2MDY2fQ.pMDeZBPmCJPXGAZ5PnfKTrusD6QUZS9Ftj0E9pYO5qs